name: Scrape EANs Parallel

on:
  # workflow_dispatch
  schedule:
    - cron: '*/10 * * * *'

jobs:
  job_1:
    name: Scrape file 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run scrape 1
        run: bash script.sh ids_00.txt
      - name: Upload products
        uses: actions/upload-artifact@v3
        with:
          name: products1
          path: tmp/*

  job_2:
   name: Scrape file 2
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Run scrape 2
       run: bash script.sh ids_01.txt
     - name: Upload products
       uses: actions/upload-artifact@v3
       with:
         name: products2
         path: tmp/*

  job_3:
   name: Scrape file 3
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Run scrape 3
       run: bash script.sh ids_02.txt
     - name: Upload products
       uses: actions/upload-artifact@v3
       with:
         name: products3
         path: tmp/*

  job_4:
   name: Scrape file 4
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Run scrape 4
       run: bash script.sh ids_03.txt
     - name: Upload products
       uses: actions/upload-artifact@v3
       with:
         name: products4
         path: tmp/*

  job_5:
    needs: [job_1, job_2, job_3, job_4]
    name: Download files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download products 1
        uses: actions/download-artifact@v3
        with:
          name: products1
          path: data
        continue-on-error: true
      - name: Download products 2
        uses: actions/download-artifact@v3
        with:
          name: products2
          path: data
        continue-on-error: true
      - name: Download products 3
        uses: actions/download-artifact@v3
        with:
          name: products3
          path: data
        continue-on-error: true
      - name: Download products 4
        uses: actions/download-artifact@v3
        with:
          name: products4
          path: data
        continue-on-error: true
      - name: Number of files in data
        run: echo "Number of files in data folder $(ls data | wc -l)"
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -m "GH ACTION Add products $(date)" || echo "Nothing to commit"
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions